"""Add image

Revision ID: 67e5ba1b2dd7
Revises: 994c72e96315
Create Date: 2023-05-16 12:46:37.714501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e5ba1b2dd7'
down_revision = '994c72e96315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birds', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
